import {
  Country,
  CountryStatuses,
} from 'src/modules/country/entities/country.entity';
import { DataSource } from 'typeorm';

const countries = [
  {
    code: 'AF',
    name: 'Afghanistan',
    country_code: '+93',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'AL',
    name: 'Albania',
    country_code: '+355',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'DZ',
    name: 'Algeria',
    country_code: '+213',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'AD',
    name: 'Andorra',
    country_code: '+376',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'AO',
    name: 'Angola',
    country_code: '+244',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'AG',
    name: 'Antigua and Barbuda',
    country_code: '+1-268',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'AR',
    name: 'Argentina',
    country_code: '+54',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'AM',
    name: 'Armenia',
    country_code: '+374',
    status: CountryStatuses.IN_ACTIVE,
  },
  { code: 'AU', name: 'Australia', country_code: '+61', status: 'active' },
  {
    code: 'AT',
    name: 'Austria',
    country_code: '+43',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'AZ',
    name: 'Azerbaijan',
    country_code: '+994',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BS',
    name: 'Bahamas',
    country_code: '+1-242',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BH',
    name: 'Bahrain',
    country_code: '+973',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    country_code: '+880',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BB',
    name: 'Barbados',
    country_code: '+1-246',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BY',
    name: 'Belarus',
    country_code: '+375',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BE',
    name: 'Belgium',
    country_code: '+32',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BZ',
    name: 'Belize',
    country_code: '+501',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BJ',
    name: 'Benin',
    country_code: '+229',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BT',
    name: 'Bhutan',
    country_code: '+975',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BO',
    name: 'Bolivia',
    country_code: '+591',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    country_code: '+387',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BW',
    name: 'Botswana',
    country_code: '+267',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BR',
    name: 'Brazil',
    country_code: '+55',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BN',
    name: 'Brunei',
    country_code: '+673',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BG',
    name: 'Bulgaria',
    country_code: '+359',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
    country_code: '+226',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BI',
    name: 'Burundi',
    country_code: '+257',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CV',
    name: 'Cabo Verde',
    country_code: '+238',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'KH',
    name: 'Cambodia',
    country_code: '+855',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CM',
    name: 'Cameroon',
    country_code: '+237',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CA',
    name: 'Canada',
    country_code: '+1',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CF',
    name: 'Central African Republic',
    country_code: '+236',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TD',
    name: 'Chad',
    country_code: '+235',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CL',
    name: 'Chile',
    country_code: '+56',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CN',
    name: 'China',
    country_code: '+86',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CO',
    name: 'Colombia',
    country_code: '+57',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'KM',
    name: 'Comoros',
    country_code: '+269',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CG',
    name: 'Congo (Congo-Brazzaville)',
    country_code: '+242',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CD',
    name: 'Congo (Democratic Republic of the Congo)',
    country_code: '+243',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CR',
    name: 'Costa Rica',
    country_code: '+506',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'HR',
    name: 'Croatia',
    country_code: '+385',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CU',
    name: 'Cuba',
    country_code: '+53',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CY',
    name: 'Cyprus',
    country_code: '+357',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CZ',
    name: 'Czech Republic (Czechia)',
    country_code: '+420',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'DK',
    name: 'Denmark',
    country_code: '+45',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'DJ',
    name: 'Djibouti',
    country_code: '+253',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'DM',
    name: 'Dominica',
    country_code: '+1-767',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'DO',
    name: 'Dominican Republic',
    country_code: '+1-809',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'EC',
    name: 'Ecuador',
    country_code: '+593',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'EG',
    name: 'Egypt',
    country_code: '+20',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SV',
    name: 'El Salvador',
    country_code: '+503',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GQ',
    name: 'Equatorial Guinea',
    country_code: '+240',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'ER',
    name: 'Eritrea',
    country_code: '+291',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'EE',
    name: 'Estonia',
    country_code: '+372',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SZ',
    name: 'Eswatini (fmr. "Swaziland")',
    country_code: '+268',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'ET',
    name: 'Ethiopia',
    country_code: '+251',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'FJ',
    name: 'Fiji',
    country_code: '+679',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'FI',
    name: 'Finland',
    country_code: '+358',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'FR',
    name: 'France',
    country_code: '+33',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GA',
    name: 'Gabon',
    country_code: '+241',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GM',
    name: 'Gambia',
    country_code: '+220',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GE',
    name: 'Georgia',
    country_code: '+995',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'DE',
    name: 'Germany',
    country_code: '+49',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GH',
    name: 'Ghana',
    country_code: '+233',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GR',
    name: 'Greece',
    country_code: '+30',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GD',
    name: 'Grenada',
    country_code: '+1-473',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GT',
    name: 'Guatemala',
    country_code: '+502',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GN',
    name: 'Guinea',
    country_code: '+224',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GW',
    name: 'Guinea-Bissau',
    country_code: '+245',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GY',
    name: 'Guyana',
    country_code: '+592',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'HT',
    name: 'Haiti',
    country_code: '+509',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'HN',
    name: 'Honduras',
    country_code: '+504',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'HU',
    name: 'Hungary',
    country_code: '+36',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'IS',
    name: 'Iceland',
    country_code: '+354',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'IN',
    name: 'India',
    country_code: '+91',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'ID',
    name: 'Indonesia',
    country_code: '+62',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'IR',
    name: 'Iran',
    country_code: '+98',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'IQ',
    name: 'Iraq',
    country_code: '+964',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'IE',
    name: 'Ireland',
    country_code: '+353',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'IL',
    name: 'Israel',
    country_code: '+972',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'IT',
    name: 'Italy',
    country_code: '+39',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'JM',
    name: 'Jamaica',
    country_code: '+1-876',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'JP',
    name: 'Japan',
    country_code: '+81',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'JO',
    name: 'Jordan',
    country_code: '+962',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'KZ',
    name: 'Kazakhstan',
    country_code: '+7',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'KE',
    name: 'Kenya',
    country_code: '+254',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'KI',
    name: 'Kiribati',
    country_code: '+686',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'KW',
    name: 'Kuwait',
    country_code: '+965',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'KG',
    name: 'Kyrgyzstan',
    country_code: '+996',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'LA',
    name: 'Laos',
    country_code: '+856',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'LV',
    name: 'Latvia',
    country_code: '+371',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'LB',
    name: 'Lebanon',
    country_code: '+961',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'LS',
    name: 'Lesotho',
    country_code: '+266',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'LR',
    name: 'Liberia',
    country_code: '+231',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'LY',
    name: 'Libya',
    country_code: '+218',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'LI',
    name: 'Liechtenstein',
    country_code: '+423',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'LT',
    name: 'Lithuania',
    country_code: '+370',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    country_code: '+352',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MO',
    name: 'Macau',
    country_code: '+853',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MK',
    name: 'Macedonia',
    country_code: '+389',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MG',
    name: 'Madagascar',
    country_code: '+261',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MW',
    name: 'Malawi',
    country_code: '+265',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MY',
    name: 'Malaysia',
    country_code: '+60',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MV',
    name: 'Maldives',
    country_code: '+960',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'ML',
    name: 'Mali',
    country_code: '+223',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MT',
    name: 'Malta',
    country_code: '+356',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MH',
    name: 'Marshall Islands',
    country_code: '+692',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MQ',
    name: 'Martinique',
    country_code: '+596',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MR',
    name: 'Mauritania',
    country_code: '+222',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MU',
    name: 'Mauritius',
    country_code: '+230',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'YT',
    name: 'Mayotte',
    country_code: '+262',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MX',
    name: 'Mexico',
    country_code: '+52',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'FM',
    name: 'Micronesia',
    country_code: '+691',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MD',
    name: 'Moldova',
    country_code: '+373',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MC',
    name: 'Monaco',
    country_code: '+377',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MN',
    name: 'Mongolia',
    country_code: '+976',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'ME',
    name: 'Montenegro',
    country_code: '+382',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MA',
    name: 'Morocco',
    country_code: '+212',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MZ',
    name: 'Mozambique',
    country_code: '+258',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MM',
    name: 'Myanmar (Burma)',
    country_code: '+95',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NA',
    name: 'Namibia',
    country_code: '+264',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NR',
    name: 'Nauru',
    country_code: '+674',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NP',
    name: 'Nepal',
    country_code: '+977',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NL',
    name: 'Netherlands',
    country_code: '+31',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NC',
    name: 'New Caledonia',
    country_code: '+687',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    country_code: '+64',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NI',
    name: 'Nicaragua',
    country_code: '+505',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NE',
    name: 'Niger',
    country_code: '+227',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NG',
    name: 'Nigeria',
    country_code: '+234',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NU',
    name: 'Niue',
    country_code: '+683',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NF',
    name: 'Norfolk Island',
    country_code: '+672',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'KP',
    name: 'North Korea',
    country_code: '+850',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MP',
    name: 'Northern Mariana Islands',
    country_code: '+1-670',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'NO',
    name: 'Norway',
    country_code: '+47',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'OM',
    name: 'Oman',
    country_code: '+968',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'PK',
    name: 'Pakistan',
    country_code: '+92',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'PW',
    name: 'Palau',
    country_code: '+680',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'PA',
    name: 'Panama',
    country_code: '+507',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'PG',
    name: 'Papua New Guinea',
    country_code: '+675',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'PY',
    name: 'Paraguay',
    country_code: '+595',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'PE',
    name: 'Peru',
    country_code: '+51',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'PH',
    name: 'Philippines',
    country_code: '+63',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'PL',
    name: 'Poland',
    country_code: '+48',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'PT',
    name: 'Portugal',
    country_code: '+351',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'PR',
    name: 'Puerto Rico',
    country_code: '+1-787',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'QA',
    name: 'Qatar',
    country_code: '+974',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'RE',
    name: 'Réunion',
    country_code: '+262',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'RO',
    name: 'Romania',
    country_code: '+40',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'RU',
    name: 'Russia',
    country_code: '+7',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'RW',
    name: 'Rwanda',
    country_code: '+250',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'BL',
    name: 'Saint Barthélemy',
    country_code: '+590',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SH',
    name: 'Saint Helena',
    country_code: '+290',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    country_code: '+1-869',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'LC',
    name: 'Saint Lucia',
    country_code: '+1-758',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'MF',
    name: 'Saint Martin',
    country_code: '+590',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'PM',
    name: 'Saint Pierre and Miquelon',
    country_code: '+508',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    country_code: '+1-784',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'WS',
    name: 'Samoa',
    country_code: '+685',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SM',
    name: 'San Marino',
    country_code: '+378',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'ST',
    name: 'São Tomé and Príncipe',
    country_code: '+239',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    country_code: '+966',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SN',
    name: 'Senegal',
    country_code: '+221',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'RS',
    name: 'Serbia',
    country_code: '+381',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SC',
    name: 'Seychelles',
    country_code: '+248',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SL',
    name: 'Sierra Leone',
    country_code: '+232',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SG',
    name: 'Singapore',
    country_code: '+65',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SX',
    name: 'Sint Maarten',
    country_code: '+1-721',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SK',
    name: 'Slovakia',
    country_code: '+421',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SI',
    name: 'Slovenia',
    country_code: '+386',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SB',
    name: 'Solomon Islands',
    country_code: '+677',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SO',
    name: 'Somalia',
    country_code: '+252',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'ZA',
    name: 'South Africa',
    country_code: '+27',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    country_code: '+500',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'KR',
    name: 'South Korea',
    country_code: '+82',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SS',
    name: 'South Sudan',
    country_code: '+211',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'ES',
    name: 'Spain',
    country_code: '+34',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'LK',
    name: 'Sri Lanka',
    country_code: '+94',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SD',
    name: 'Sudan',
    country_code: '+249',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SR',
    name: 'Suriname',
    country_code: '+597',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SJ',
    name: 'Svalbard and Jan Mayen',
    country_code: '+47',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SE',
    name: 'Sweden',
    country_code: '+46',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'CH',
    name: 'Switzerland',
    country_code: '+41',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'SY',
    name: 'Syria',
    country_code: '+963',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TW',
    name: 'Taiwan',
    country_code: '+886',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TJ',
    name: 'Tajikistan',
    country_code: '+992',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TZ',
    name: 'Tanzania',
    country_code: '+255',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TH',
    name: 'Thailand',
    country_code: '+66',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TL',
    name: 'Timor-Leste',
    country_code: '+670',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TG',
    name: 'Togo',
    country_code: '+228',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TK',
    name: 'Tokelau',
    country_code: '+690',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TO',
    name: 'Tonga',
    country_code: '+676',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TT',
    name: 'Trinidad and Tobago',
    country_code: '+1-868',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TN',
    name: 'Tunisia',
    country_code: '+216',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TR',
    name: 'Turkey',
    country_code: '+90',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TM',
    name: 'Turkmenistan',
    country_code: '+993',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TC',
    name: 'Turks and Caicos Islands',
    country_code: '+1-649',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'TV',
    name: 'Tuvalu',
    country_code: '+688',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'UG',
    name: 'Uganda',
    country_code: '+256',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'UA',
    name: 'Ukraine',
    country_code: '+380',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    country_code: '+971',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    country_code: '+44',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'US',
    name: 'United States',
    country_code: '+1',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'UY',
    name: 'Uruguay',
    country_code: '+598',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'UZ',
    name: 'Uzbekistan',
    country_code: '+998',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'VU',
    name: 'Vanuatu',
    country_code: '+678',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'VE',
    name: 'Venezuela',
    country_code: '+58',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'VN',
    name: 'Vietnam',
    country_code: '+84',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'WF',
    name: 'Wallis and Futuna',
    country_code: '+681',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'EH',
    name: 'Western Sahara',
    country_code: '+212',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'YE',
    name: 'Yemen',
    country_code: '+967',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'ZM',
    name: 'Zambia',
    country_code: '+260',
    status: CountryStatuses.IN_ACTIVE,
  },
  {
    code: 'ZW',
    name: 'Zimbabwe',
    country_code: '+263',
    status: CountryStatuses.IN_ACTIVE,
  },
];

export const createCountries = async (AppDataSource: DataSource) => {
  const countryRepository = AppDataSource.getRepository(Country);

  for (const { name, code, country_code, status } of countries) {
    const isCountryAlreadyExist = await countryRepository.findOne({
      where: {
        name,
      },
    });

    if (!isCountryAlreadyExist) {
      const country = countryRepository.create({
        name,
        code,
        country_code,
        status: CountryStatuses[status],
      });

      await country.save();
    }
  }

  console.log('All countries seeded successfully');
};
